// lib/core/utils/translation_helper.dart
class TranslationHelper {
  static String getText(String key, String languageCode) {
    final translations = {
      'en': {
        'balance': 'Balance',
        'income': 'Income',
        'expenses': 'Expenses',
        'total_spent': 'Total Spent',
        'avg_daily': 'Avg Daily',
        'add_expense': 'Add Expense',
        'add_income': 'Add Income',
        'recent_transactions': 'Recent Transactions',
        'view_all': 'View All',
        'no_transactions': 'No Transactions Yet',
        'quick_actions': 'Quick Actions',
        'this_month': 'This Month',
        'this_year': 'This Year',
        'analytics': 'Analytics',
        'budget': 'Budget',
        'budget_categories': 'Budget Categories',
        'budget_overview': 'Overview',
        'budget_insights': 'Budget Insights',
        'over_budget': 'Over Budget',
        'over_by': 'Over by',
        'unknown_category': 'Unknown Category',
        'delete_budget': 'Delete Budget',
        'edit_budget': 'Edit Budget',
        'delete_budget_confirmation': 'Are you sure you want to delete this budget?',
        'cancel': 'Cancel',
        'delete': 'Delete',
        'close': 'Close',
        'edit': 'Edit',
        'notes': 'Notes',
        'budget_amount': 'Budget Amount',
        'amount_spent': 'Amount Spent',
        'create_first_budget': 'Create your first budget to start tracking your spending goals.',
        'over_budget_alert': 'Over Budget Alert',
        'approaching_limit': 'Approaching Limit',
        'on_track': 'On Track',
        'category_is': 'category is',
        'categories_are': 'categories are',
        'near_budget_limit': 'near budget limit',
        'well_within_budget': 'well within budget',
        'add_transaction': 'Add Transaction',
        'expense': 'Expense',
        'title': 'Title',
        'amount': 'Amount',
        'category': 'Category',
        'date': 'Date',
        'description_optional': 'Description (Optional)',
        'enter_title': 'Enter title',
        'reset': 'Reset',
        'saving': 'Saving...',
        'please_select_category': 'Please select a category',
        'user_not_authenticated': 'User not authenticated',
        'expense_added_successfully': 'Expense added successfully!',
        'income_added_successfully': 'Income added successfully!',
        'failed_to_save': 'Failed to save',
        'please_enter_title': 'Please enter a title',
        'please_enter_amount': 'Please enter an amount',
        'please_enter_valid_amount': 'Please enter a valid amount',
        'no_categories_available': 'No categories available',
        'add_category': 'Add Category',
        'more_categories': 'More Categories',
        'all_categories': 'All Categories',
        'add_custom_category': 'Add Custom Category',
        'add_note_transaction': 'Add a note about this transaction',
        'total_budget': 'Total Budget',
        'spent': 'Spent',
        'remaining': 'Remaining',
        'create_budget': 'Create Budget',
        'add_budget': 'Add Budget',
        'budget_progress': 'Budget Progress',
        'no_budget_set': 'No Budgets Set',
        'monthly': 'Monthly',
        'yearly': 'Yearly',
        'select_category': 'Select Category',
        'please_enter_budget_amount': 'Please enter budget amount',
        'notes_optional': 'Notes (Optional)',
        'add_budget_notes': 'Add notes about this budget...',
        'update_budget': 'Update Budget',
        'budget_updated_successfully': 'Budget updated successfully',
        'budget_created_successfully': 'Budget created successfully',
        'budget_deleted_successfully': 'Budget deleted successfully',
        'failed_to_delete': 'Failed to delete budget:',
        'this_week': 'This Week',
        'last_3_months': 'Last 3 Months',
        'overview': 'Overview',
        'categories': 'Categories',
        'trends': 'Trends',
        'transactions': 'Transactions',
        'spending_overview': 'Spending Overview',
        'highest_expenses': 'Highest Expenses',
        'category_breakdown': 'Category Breakdown',
        'spending_trend': 'Spending Trend',
        'weekly_comparison': 'Weekly Comparison',
        'no_data_available': 'No data available',
        'no_expenses_found': 'No expenses found',
        'unknown': 'Unknown',
        'week': 'Week',
        'all': 'All',
        'no_transactions_found': 'No transactions found',
        'add_first_transaction': 'Add your first transaction to get started',
        'expense_deleted_successfully': 'Expense deleted successfully',
        'failed_to_delete_expense': 'Failed to delete expense',
        'delete_expense': 'Delete Expense',
        'delete_expense_confirmation': 'Are you sure you want to delete this expense?',
        'transaction_details': 'Transaction Details',
        'type': 'Type',
        'description': 'Description',
        'hello': 'Hello',
        'good_morning': 'Good Morning',
        'good_afternoon': 'Good Afternoon',
        'good_evening': 'Good Evening',
        'user': 'User',
        'notifications_coming_soon': 'Notifications coming soon!',
        'settings': 'Settings',
        'profile': 'Profile',
        'sign_out': 'Sign Out',
        'total_balance': 'Total Balance',
        'view_budget': 'View Budget',
        'no_transactions_yet': 'No Transactions Yet',
        'start_tracking_expenses': 'Start tracking your expenses by adding your first transaction',
        'app_preferences': 'App Preferences',
        'theme': 'Theme',
        'language': 'Language',
        'currency': 'Currency',
        'security_privacy': 'Security & Privacy',
        'push_notifications': 'Push Notifications',
        'biometric_login': 'Biometric Login',
        'change_password': 'Change Password',
        'support_information': 'Support & Information',
        'help_center': 'Help Center',
        'send_feedback': 'Send Feedback',
        'about': 'About',
        'payment_methods': 'Payment Methods',
        'transaction_history': 'Transaction History',
        'enabled': 'Enabled',
        'disabled': 'Disabled',
        'system': 'System',
        'light': 'Light',
        'dark': 'Dark',
        'light_mode': 'Light Mode',
        'dark_mode': 'Dark Mode',
        'system_default': 'System Default',
        'english': 'English',
        'spanish': 'Spanish',
        'french': 'French',
        'sign_out_confirmation': 'Are you sure you want to sign out?',
        'current_password': 'Current Password',
        'new_password': 'New Password',
        'enter_current_password': 'Enter current password',
        'password_min_length': 'Password must be at least 6 characters',
        'update': 'Update',
        'password_updated_successfully': 'Password updated successfully',
        'failed_to_update_password': 'Failed to update password',
        'biometric_not_supported': 'Biometric authentication not supported',
        'no_biometrics_enrolled': 'No biometrics enrolled on this device',
        'authenticate_enable_biometric': 'Authenticate to enable biometric login',
        'biometric_enabled': 'Biometric authentication enabled',
        'biometric_disabled': 'Biometric authentication disabled',
        'authentication_error': 'Authentication error',
        'authentication_failed': 'Authentication failed',
        'update_account_password': 'Update your account password',
        'faqs_guides': 'FAQs and guides',
        'share_thoughts': 'Share your thoughts',
        'version_info': 'Version 1.0.0',
      },
      'es': {
        'balance': 'Saldo',
        'income': 'Ingresos',
        'expenses': 'Gastos',
        'total_spent': 'Total Gastado',
        'avg_daily': 'Promedio Diario',
        'add_expense': 'Agregar Gasto',
        'add_income': 'Agregar Ingreso',
        'recent_transactions': 'Transacciones Recientes',
        'view_all': 'Ver Todo',
        'no_transactions': 'Sin Transacciones',
        'quick_actions': 'Acciones Rápidas',
        'this_month': 'Este Mes',
        'this_year': 'Este Año',
        'analytics': 'Análisis',
        'budget': 'Presupuesto',
        'budget_categories': 'Categorías de Presupuesto',
        'budget_overview': 'Resumen',
        'budget_insights': 'Análisis del Presupuesto',
        'over_budget': 'Sobre Presupuesto',
        'over_by': 'Excedido por',
        'unknown_category': 'Categoría Desconocida',
        'delete_budget': 'Eliminar Presupuesto',
        'edit_budget': 'Editar Presupuesto',
        'delete_budget_confirmation': '¿Está seguro de que desea eliminar este presupuesto?',
        'cancel': 'Cancelar',
        'delete': 'Eliminar',
        'close': 'Cerrar',
        'edit': 'Editar',
        'notes': 'Notas',
        'budget_amount': 'Cantidad del Presupuesto',
        'amount_spent': 'Cantidad Gastada',
        'create_first_budget': 'Crea tu primer presupuesto para comenzar a rastrear tus objetivos de gasto.',
        'over_budget_alert': 'Alerta de Presupuesto Excedido',
        'approaching_limit': 'Acercándose al Límite',
        'on_track': 'En Buen Camino',
        'category_is': 'categoría está',
        'categories_are': 'categorías están',
        'near_budget_limit': 'cerca del límite del presupuesto',
        'well_within_budget': 'muy dentro del presupuesto',
        'add_transaction': 'Agregar Transacción',
        'expense': 'Gasto',
        'title': 'Título',
        'amount': 'Cantidad',
        'category': 'Categoría',
        'date': 'Fecha',
        'description_optional': 'Descripción (Opcional)',
        'enter_title': 'Ingrese título',
        'reset': 'Restablecer',
        'saving': 'Guardando...',
        'please_select_category': 'Por favor seleccione una categoría',
        'user_not_authenticated': 'Usuario no autenticado',
        'expense_added_successfully': '¡Gasto agregado exitosamente!',
        'income_added_successfully': '¡Ingreso agregado exitosamente!',
        'failed_to_save': 'Error al guardar',
        'please_enter_title': 'Por favor ingrese un título',
        'please_enter_amount': 'Por favor ingrese una cantidad',
        'please_enter_valid_amount': 'Por favor ingrese una cantidad válida',
        'no_categories_available': 'No hay categorías disponibles',
        'add_category': 'Agregar Categoría',
        'more_categories': 'Más Categorías',
        'all_categories': 'Todas las Categorías',
        'add_custom_category': 'Agregar Categoría Personalizada',
        'add_note_transaction': 'Agregue una nota sobre esta transacción',
        'total_budget': 'Presupuesto Total',
        'spent': 'Gastado',
        'remaining': 'Restante',
        'create_budget': 'Crear Presupuesto',
        'add_budget': 'Agregar Presupuesto',
        'budget_progress': 'Progreso del Presupuesto',
        'no_budget_set': 'Sin Presupuestos',
        'monthly': 'Mensual',
        'yearly': 'Anual',
        'select_category': 'Seleccionar Categoría',
        'please_enter_budget_amount': 'Por favor ingrese el monto del presupuesto',
        'notes_optional': 'Notas (Opcional)',
        'add_budget_notes': 'Agregue notas sobre este presupuesto...',
        'update_budget': 'Actualizar Presupuesto',
        'budget_updated_successfully': 'Presupuesto actualizado exitosamente',
        'budget_created_successfully': 'Presupuesto creado exitosamente',
        'budget_deleted_successfully': 'Presupuesto eliminado exitosamente',
        'failed_to_delete': 'Error al eliminar presupuesto:',
        'this_week': 'Esta Semana',
        'last_3_months': 'Últimos 3 Meses',
        'overview': 'Resumen',
        'categories': 'Categorías',
        'trends': 'Tendencias',
        'transactions': 'Transacciones',
        'spending_overview': 'Resumen de Gastos',
        'highest_expenses': 'Gastos Más Altos',
        'category_breakdown': 'Desglose por Categoría',
        'spending_trend': 'Tendencia de Gastos',
        'weekly_comparison': 'Comparación Semanal',
        'no_data_available': 'No hay datos disponibles',
        'no_expenses_found': 'No se encontraron gastos',
        'unknown': 'Desconocido',
        'week': 'Semana',
        'all': 'Todos',
        'no_transactions_found': 'No se encontraron transacciones',
        'add_first_transaction': 'Agregue su primera transacción para comenzar',
        'expense_deleted_successfully': 'Gasto eliminado exitosamente',
        'failed_to_delete_expense': 'Error al eliminar gasto',
        'delete_expense': 'Eliminar Gasto',
        'delete_expense_confirmation': '¿Está seguro de que desea eliminar este gasto?',
        'transaction_details': 'Detalles de Transacción',
        'type': 'Tipo',
        'description': 'Descripción',
        'hello': 'Hola',
        'good_morning': 'Buenos Días',
        'good_afternoon': 'Buenas Tardes',
        'good_evening': 'Buenas Noches',
        'user': 'Usuario',
        'notifications_coming_soon': '¡Notificaciones próximamente!',
        'settings': 'Configuración',
        'profile': 'Perfil',
        'sign_out': 'Cerrar Sesión',
        'total_balance': 'Balance Total',
        'view_budget': 'Ver Presupuesto',
        'no_transactions_yet': 'Sin Transacciones Aún',
        'start_tracking_expenses': 'Comience a rastrear sus gastos agregando su primera transacción',
        'app_preferences': 'Preferencias de Aplicación',
        'theme': 'Tema',
        'language': 'Idioma',
        'currency': 'Moneda',
        'security_privacy': 'Seguridad y Privacidad',
        'push_notifications': 'Notificaciones Push',
        'biometric_login': 'Inicio Biométrico',
        'change_password': 'Cambiar Contraseña',
        'support_information': 'Soporte e Información',
        'help_center': 'Centro de Ayuda',
        'send_feedback': 'Enviar Comentarios',
        'about': 'Acerca de',
        'payment_methods': 'Métodos de Pago',
        'transaction_history': 'Historial de Transacciones',
        'enabled': 'Habilitado',
        'disabled': 'Deshabilitado',
        'system': 'Sistema',
        'light': 'Claro',
        'dark': 'Oscuro',
        'light_mode': 'Modo Claro',
        'dark_mode': 'Modo Oscuro',
        'system_default': 'Predeterminado del Sistema',
        'english': 'Inglés',
        'spanish': 'Español',
        'french': 'Francés',
        'sign_out_confirmation': '¿Está seguro de que desea cerrar sesión?',
        'current_password': 'Contraseña Actual',
        'new_password': 'Nueva Contraseña',
        'enter_current_password': 'Ingrese la contraseña actual',
        'password_min_length': 'La contraseña debe tener al menos 6 caracteres',
        'update': 'Actualizar',
        'password_updated_successfully': 'Contraseña actualizada exitosamente',
        'failed_to_update_password': 'Error al actualizar la contraseña',
        'biometric_not_supported': 'Autenticación biométrica no compatible',
        'no_biometrics_enrolled': 'No hay biométricos registrados en este dispositivo',
        'authenticate_enable_biometric': 'Autentíquese para habilitar el inicio biométrico',
        'biometric_enabled': 'Autenticación biométrica habilitada',
        'biometric_disabled': 'Autenticación biométrica deshabilitada',
        'authentication_error': 'Error de autenticación',
        'authentication_failed': 'Autenticación fallida',
        'update_account_password': 'Actualice la contraseña de su cuenta',
        'faqs_guides': 'Preguntas frecuentes y guías',
        'share_thoughts': 'Comparta sus pensamientos',
        'version_info': 'Versión 1.0.0',
      },
      'fr': {
        'balance': 'Solde',
        'income': 'Revenus',
        'expenses': 'Dépenses',
        'total_spent': 'Total Dépensé',
        'avg_daily': 'Moyenne Quotidienne',
        'add_expense': 'Ajouter Dépense',
        'add_income': 'Ajouter Revenu',
        'recent_transactions': 'Transactions Récentes',
        'view_all': 'Voir Tout',
        'no_transactions': 'Aucune Transaction',
        'quick_actions': 'Actions Rapides',
        'this_month': 'Ce Mois',
        'this_year': 'Cette Année',
        'analytics': 'Analytique',
        'budget': 'Budget',
        'budget_categories': 'Catégories de Budget',
        'budget_overview': 'Aperçu',
        'budget_insights': 'Analyses du Budget',
        'over_budget': 'Hors Budget',
        'over_by': 'Dépassé de',
        'unknown_category': 'Catégorie Inconnue',
        'delete_budget': 'Supprimer Budget',
        'edit_budget': 'Modifier Budget',
        'delete_budget_confirmation': 'Êtes-vous sûr de vouloir supprimer ce budget?',
        'cancel': 'Annuler',
        'delete': 'Supprimer',
        'close': 'Fermer',
        'edit': 'Modifier',
        'notes': 'Notes',
        'budget_amount': 'Montant du Budget',
        'amount_spent': 'Montant Dépensé',
        'create_first_budget': 'Créez votre premier budget pour commencer à suivre vos objectifs de dépenses.',
        'over_budget_alert': 'Alerte Budget Dépassé',
        'approaching_limit': 'Approche de la Limite',
        'on_track': 'Sur la Bonne Voie',
        'category_is': 'catégorie est',
        'categories_are': 'catégories sont',
        'near_budget_limit': 'près de la limite du budget',
        'well_within_budget': 'bien dans le budget',
        'add_transaction': 'Ajouter Transaction',
        'expense': 'Dépense',
        'title': 'Titre',
        'amount': 'Montant',
        'category': 'Catégorie',
        'date': 'Date',
        'description_optional': 'Description (Optionnel)',
        'enter_title': 'Entrez le titre',
        'reset': 'Réinitialiser',
        'saving': 'Enregistrement...',
        'please_select_category': 'Veuillez sélectionner une catégorie',
        'user_not_authenticated': 'Utilisateur non authentifié',
        'expense_added_successfully': 'Dépense ajoutée avec succès!',
        'income_added_successfully': 'Revenu ajouté avec succès!',
        'failed_to_save': 'Échec de l\'enregistrement',
        'please_enter_title': 'Veuillez entrer un titre',
        'please_enter_amount': 'Veuillez entrer un montant',
        'please_enter_valid_amount': 'Veuillez entrer un montant valide',
        'no_categories_available': 'Aucune catégorie disponible',
        'add_category': 'Ajouter Catégorie',
        'more_categories': 'Plus de Catégories',
        'all_categories': 'Toutes les Catégories',
        'add_custom_category': 'Ajouter Catégorie Personnalisée',
        'add_note_transaction': 'Ajoutez une note sur cette transaction',
        'total_budget': 'Budget Total',
        'spent': 'Dépensé',
        'remaining': 'Restant',
        'create_budget': 'Créer Budget',
        'add_budget': 'Ajouter Budget',
        'budget_progress': 'Progrès du Budget',
        'no_budget_set': 'Aucun Budget Défini',
        'monthly': 'Mensuel',
        'yearly': 'Annuel',
        'select_category': 'Sélectionner Catégorie',
        'please_enter_budget_amount': 'Veuillez entrer le montant du budget',
        'notes_optional': 'Notes (Optionnel)',
        'add_budget_notes': 'Ajoutez des notes sur ce budget...',
        'update_budget': 'Mettre à Jour Budget',
        'budget_updated_successfully': 'Budget mis à jour avec succès',
        'budget_created_successfully': 'Budget créé avec succès',
        'budget_deleted_successfully': 'Budget supprimé avec succès',
        'failed_to_delete': 'Échec de la suppression du budget:',
        'this_week': 'Cette Semaine',
        'last_3_months': 'Derniers 3 Mois',
        'overview': 'Aperçu',
        'categories': 'Catégories',
        'trends': 'Tendances',
        'transactions': 'Transactions',
        'spending_overview': 'Aperçu des Dépenses',
        'highest_expenses': 'Dépenses les Plus Élevées',
        'category_breakdown': 'Répartition par Catégorie',
        'spending_trend': 'Tendance des Dépenses',
        'weekly_comparison': 'Comparaison Hebdomadaire',
        'no_data_available': 'Aucune donnée disponible',
        'no_expenses_found': 'Aucune dépense trouvée',
        'unknown': 'Inconnu',
        'week': 'Semaine',
        'all': 'Tous',
        'no_transactions_found': 'Aucune transaction trouvée',
        'add_first_transaction': 'Ajoutez votre première transaction pour commencer',
        'expense_deleted_successfully': 'Dépense supprimée avec succès',
        'failed_to_delete_expense': 'Échec de la suppression de la dépense',
        'delete_expense': 'Supprimer Dépense',
        'delete_expense_confirmation': 'Êtes-vous sûr de vouloir supprimer cette dépense?',
        'transaction_details': 'Détails de Transaction',
        'type': 'Type',
        'description': 'Description',
        'hello': 'Bonjour',
        'good_morning': 'Bonjour',
        'good_afternoon': 'Bon Après-midi',
        'good_evening': 'Bonsoir',
        'user': 'Utilisateur',
        'notifications_coming_soon': 'Notifications bientôt disponibles !',
        'settings': 'Paramètres',
        'profile': 'Profil',
        'sign_out': 'Se Déconnecter',
        'total_balance': 'Solde Total',
        'view_budget': 'Voir Budget',
        'no_transactions_yet': 'Aucune Transaction Encore',
        'start_tracking_expenses': 'Commencez à suivre vos dépenses en ajoutant votre première transaction',
        'app_preferences': 'Préférences de l\'Application',
        'theme': 'Thème',
        'language': 'Langue',
        'currency': 'Devise',
        'security_privacy': 'Sécurité et Confidentialité',
        'push_notifications': 'Notifications Push',
        'biometric_login': 'Connexion Biométrique',
        'change_password': 'Changer Mot de Passe',
        'support_information': 'Support et Information',
        'help_center': 'Centre d\'Aide',
        'send_feedback': 'Envoyer Commentaires',
        'about': 'À Propos',
        'payment_methods': 'Méthodes de Paiement',
        'transaction_history': 'Historique des Transactions',
        'enabled': 'Activé',
        'disabled': 'Désactivé',
        'system': 'Système',
        'light': 'Clair',
        'dark': 'Sombre',
        'light_mode': 'Mode Clair',
        'dark_mode': 'Mode Sombre',
        'system_default': 'Par Défaut du Système',
        'english': 'Anglais',
        'spanish': 'Espagnol',
        'french': 'Français',
        'sign_out_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
        'current_password': 'Mot de Passe Actuel',
        'new_password': 'Nouveau Mot de Passe',
        'enter_current_password': 'Entrez le mot de passe actuel',
        'password_min_length': 'Le mot de passe doit comporter au moins 6 caractères',
        'update': 'Mettre à Jour',
        'password_updated_successfully': 'Mot de passe mis à jour avec succès',
        'failed_to_update_password': 'Échec de la mise à jour du mot de passe',
        'biometric_not_supported': 'Authentification biométrique non prise en charge',
        'no_biometrics_enrolled': 'Aucune biométrie enregistrée sur cet appareil',
        'authenticate_enable_biometric': 'Authentifiez-vous pour activer la connexion biométrique',
        'biometric_enabled': 'Authentification biométrique activée',
        'biometric_disabled': 'Authentification biométrique désactivée',
        'authentication_error': 'Erreur d\'authentification',
        'authentication_failed': 'Échec de l\'authentification',
        'update_account_password': 'Mettez à jour le mot de passe de votre compte',
        'faqs_guides': 'FAQ et guides',
        'share_thoughts': 'Partagez vos pensées',
        'version_info': 'Version 1.0.0',

        // Onboarding screen translations
        'onboarding_title_1': 'Suivez Vos Dépenses',
        'onboarding_desc_1': 'Surveillez facilement vos habitudes de dépenses et prenez le contrôle de votre vie financière avec notre suivi intuitif des dépenses.',
        'onboarding_title_2': 'Analyses Intelligentes',
        'onboarding_desc_2': 'Obtenez des informations détaillées sur vos habitudes de dépenses avec de beaux graphiques et des rapports complets.',
        'onboarding_title_3': 'Sécurisé et Privé',
        'onboarding_desc_3': 'Vos données financières sont cryptées et sécurisées. Nous priorisons votre vie privée et la protection des données.',
        'skip': 'Passer',
        'back': 'Retour',
        'next': 'Suivant',
        'get_started': 'Commencer',
      },
    };

    // Return the translated text or fallback to 'en' or the key itself
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}