// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZsHrlVhk1Of-S-qoicuOVDNhLAEDrguU',
    appId: '1:1035536884162:web:6ac697ac52d57748f2b65b',
    messagingSenderId: '1035536884162',
    projectId: 'expense-tracker-fa8d0',
    authDomain: 'expense-tracker-fa8d0.firebaseapp.com',
    storageBucket: 'expense-tracker-fa8d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbggWvziJ2xt8MN3PUiQ4ScpCyVZ3IV4',
    appId: '1:1035536884162:android:5565cdf99891092af2b65b',
    messagingSenderId: '1035536884162',
    projectId: 'expense-tracker-fa8d0',
    storageBucket: 'expense-tracker-fa8d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB59_FSUFowiG0FltGyDBqtERvb-OgbueI',
    appId: '1:1035536884162:ios:2b9221bb80861c9ef2b65b',
    messagingSenderId: '1035536884162',
    projectId: 'expense-tracker-fa8d0',
    storageBucket: 'expense-tracker-fa8d0.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
